  version: 2
  updates:
  - package-ecosystem: "npm"
    directory: "/packages/driver"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-api"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-cypress"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-images"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-nightwatch"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-playwright"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-protractor"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-puppeteer"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-sdk-core"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-selenium"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-storybook"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-testcafe"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-universal"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-webdriverio-4"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-webdriverio-4-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-webdriverio-5"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/eyes-webdriverio-5-service"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/fancy"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/screenshoter"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/sdk-coverage-tests"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/sdk-fake-eyes-server"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/sdk-release-kit"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/sdk-shared"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/side-eyes"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/snaptdout"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/snippets"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/utils"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/packages/visual-grid-client"
    schedule:
      interval: "daily"
