name: .changelog

on: pull_request

jobs:
  changelog:
    runs-on: ubuntu-latest
    name: changelog
    steps:
      - uses: actions/checkout@v2
        if: "!contains(github.event.head_commit.message, '[Security]')"
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          # git diff exits w/ 0 when there are no changes found (hence the counter-intuitive negation)
          if ! git diff --quiet pending-changes.yaml; then
            exit 1
          fi
          cd packages/
          packages=$(git diff HEAD~ --name-only | cut -d "/" -f 2 | uniq)
          for package in $packages; do
            if [[ -f "$package/CHANGELOG.md" ]]; then
              cd $package
              echo "::group::installing deps for $package"
                yarn
              echo "::endgroup::"
              echo "::group::verifying changelog for $package"
                yarn bongo verify-changelog
              echo "::endgroup::"
              cd ../
            fi
          done
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
