name: Verify changelog

on: 
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore: ['dependabot/**']

jobs:
  verify:
    if: ${{github.actor != 'dependabot[bot]' && !github.event.pull_request.draft}}
    runs-on: ubuntu-latest
    name: Verify changelog
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Verify changelog
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
          if [[ $(git log origin/master... --grep=NO_CHANGELOG | wc -l) -gt 0 ]]; then
            echo NO_CHANGELOG commit tag found. Skipping changelog check.
            exit 0
          fi
          # git diff --quiet leads to no output and an exit code based on the result
          # when there are no diffs, the exit code is 0 (true)
          # when there are diffs, the exit code is 1 (false)
          if git diff --quiet HEAD~ pending-changes.yaml; then
            echo No updates to pending-changes.yaml detected. Add an entry to this file for the relevant SDKs as part of this PR
            exit 1
          fi
          cd js/packages/
          packages=$(git diff HEAD~ --name-only | cut -d "/" -f 2 | uniq)
          for package in $packages; do
            if [[ -f "$package/CHANGELOG.md" ]]; then
              cd $package
              echo "::group::installing deps for $package"
                yarn
              echo "::endgroup::"
              echo "::group::verifying changelog for $package"
                yarn bongo verify-changelog
              echo "::endgroup::"
              cd ../
            fi
          done
