name: Publish (do not use)

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases)
        required: true
      version:
        description: version type
        type: choice
        options: [ patch, minor, major ]
        default: patch
      allow-cascading:
        description: include dependencies
        type: boolean
        default: true
      only-changed:
        description: include only packages with new commits
        type: boolean
        default: true
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  CVG_TESTS_EG_REMOTE: ${{secrets.CVG_TESTS_EG_REMOTE}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  FORCE_COLOR: 3
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          allow-cascading: ${{github.event.inputs.allow-cascading}}
          only-changed: ${{github.event.inputs.only-changed}}
          release-version: ${{github.event.inputs.version}}

  # INTERNAL
  types:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).types && !failure() && !cancelled()}}
    name: types
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-types.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).types.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  utils:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).utils && !failure() && !cancelled()}}
    name: utils
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-utils.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).utils.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  logger:
    needs: [ setup, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).logger && !failure() && !cancelled()}}
    name: logger
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-logger.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).logger.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  snippets:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).snippets && !failure() && !cancelled()}}
    name: snippets
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-snippets.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).snippets.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  screenshoter:
    needs:
      [
        setup,
        logger,
        snippets,
        utils,
        driver,
        spec-webdriverio,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).screenshoter && !failure() && !cancelled()}}
    name: screenshoter
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-screenshoter.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).screenshoter.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  driver:
    needs: [ setup, logger, snippets, types, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).driver && !failure() && !cancelled()}}
    name: driver
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-driver.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).driver.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

  # CORE
  core:
    needs:
      [
        setup,
        driver,
        eg-client,
        logger,
        screenshoter,
        snippets,
        types,
        utils,
        spec-selenium,
        test-server,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).core && !failure() && !cancelled()}}
    name: core
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-core.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).core.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  ufg-client:
    needs: [ setup, core, logger, test-server, test-utils, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).ufg-client && !failure() && !cancelled()}}
    name: ufg-client
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-ufg-client.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).ufg-client.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  eg-client:
    needs: [ setup, logger, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).eg-client && !failure() && !cancelled()}}
    name: eg-client
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-eg-client.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).eg-client.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  universal:
    needs:
      [
        setup,
        eg-client,
        core,
        logger,
        utils,
        ufg-client,
        test-utils,
        types
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).universal && !failure() && !cancelled()}}
    name: universal
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-universal.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).universal.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  api:
    needs: [ setup, logger, types, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).api && !failure() && !cancelled()}}
    name: api
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-api.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).api.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

  # SPEC DRIVERS
  spec-playwright:
    needs: [ setup, types, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-playwright && !failure() && !cancelled()}}
    name: spec-playwright
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-playwright.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-playwright.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  spec-puppeteer:
    needs: [ setup, types, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-puppeteer && !failure() && !cancelled()}}
    name: spec-puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-puppeteer.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-puppeteer.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  spec-selenium:
    needs: [ setup, types, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-selenium && !failure() && !cancelled()}}
    name: spec-selenium
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-selenium.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-selenium.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  spec-webdriverio:
    needs: [ setup, types, utils, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).spec-webdriverio && !failure() && !cancelled()}}
    name: spec-webdriverio
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-spec-webdriverio.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).spec-webdriverio.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

  # SDKS
  playwright:
    needs:
      [
        setup,
        api,
        core,
        spec-playwright,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).playwright && !failure() && !cancelled()}}
    name: playwright
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-playwright.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).playwright.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  puppeteer:
    needs:
      [
        setup,
        api,
        core,
        spec-puppeteer,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).puppeteer && !failure() && !cancelled()}}
    name: puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-puppeteer.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).puppeteer.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  webdriverio:
    needs:
      [
        setup,
        api,
        core,
        spec-webdriverio,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).webdriverio && !failure() && !cancelled()}}
    name: webdriverio
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-webdriverio.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).webdriverio.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  selenium:
    needs:
      [
        setup,
        api,
        core,
        spec-selenium,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).selenium && !failure() && !cancelled()}}
    name: selenium
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-selenium.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).selenium.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  protractor:
    needs:
      [
        setup,
        api,
        core,
        types,
        utils,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).protractor && !failure() && !cancelled()}}
    name: protractor
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-protractor.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).protractor.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  nightwatch:
    needs:
      [
        setup,
        api,
        core,
        types,
        utils,
        ufg-client,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).nightwatch && !failure() && !cancelled()}}
    name: nightwatch
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-nightwatch.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).nightwatch.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  testcafe:
    needs:
      [
        setup,
        api,
        core,
        utils,
        ufg-client,
        test-server,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).testcafe && !failure() && !cancelled()}}
    name: testcafe
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-testcafe.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).testcafe.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  cypress:
    needs:
      [
        setup,
        api,
        universal,
        logger,
        ufg-client,
        test-server,
        test-utils,
        types,
        utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).cypress && !failure() && !cancelled()}}
    name: cypress
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-cypress.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).cypress.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  browser-extension:
    needs:
      [
        setup,
        core,
        utils,
        ufg-client,
        spec-playwright,
        test-utils
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).browser-extension && !failure() && !cancelled()}}
    name: browser-extension
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-browser-extension.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).browser-extension.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  storybook:
    needs:
      [
        setup,
        driver,
        core,
        logger,
        spec-puppeteer,
        test-server,
        utils,
        ufg-client
      ]
    if: ${{fromJSON(needs.setup.outputs.packages).storybook && !failure() && !cancelled()}}
    name: storybook
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-storybook.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).storybook.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

  # SDK WRAPPERS
  webdriverio-service:
    needs: [ setup, webdriverio, test-utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).webdriverio-service && !failure() && !cancelled()}}
    name: webdriverio-service
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-webdriverio-service.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).webdriverio-service.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}

  # TESTING BASE
  test-utils:
    needs: [ setup ]
    if: ${{fromJSON(needs.setup.outputs.packages).test-utils && !failure() && !cancelled()}}
    name: test-utils
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-test-utils.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).test-utils.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
  test-server:
    needs: [ setup, utils ]
    if: ${{fromJSON(needs.setup.outputs.packages).test-server && !failure() && !cancelled()}}
    name: test-server
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Run remote workflow
        uses: ./.github/actions/run
        with:
          workflow: publish-test-server.yml
          inputs: '{"version": "${{fromJSON(needs.setup.outputs.packages).test-server.version}}"}'
        env:
          GITHUB_TOKEN: ${{secrets.RUN_GITHUB_TOKEN}}
