name: Publish - nml client

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
    secrets:
      NPM_TOKEN:
        required: true

env:
  FORCE_COLOR: 3
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/nml-client
  publish:
    name: Publish
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          working-directory: ./js/packages/nml-client
          version: ${{inputs.version || github.event.inputs.version}}
