name: Publish - sdk nightwatch

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
      multienv:
        description: test on multiple environments
        type: boolean
        default: true
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
    secrets:
      NPM_TOKEN:
        required: true
      APPLITOOLS_API_KEY:
        required: true
      APPLITOOLS_API_KEY_READ:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true
      AZURE_STORAGE_CONNECTION_STRING:
        required: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}

jobs:
  verify:
    name: Verification
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.prepare.outputs.environments}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run pre-publish verifications
        shell: bash
        working-directory: ./js/packages/eyes-nightwatch
        run: |
          yarn install
          npx bongo release-pre-check --skip-deps --skip-commit --skip-verify-installed-versions
          npx bongo verify-changelog
      - name: Prepare environments
        id: prepare
        shell: bash
        run: |
          if [ ${{github.event.inputs.multienv}} = true ]
          then
            echo "::set-output name=environments::[{\"framework-version\":1,\"node-version\":16}, {\"framework-version\":2,\"node-version\":16}, {\"framework-version\":1,\"node-version\":14}, {\"framework-version\":2,\"node-version\":14}, {\"framework-version\":1,\"node-version\":12}, {\"framework-version\":2,\"node-version\":12}]"
          else
            echo "::set-output name=environments::[{\"framework-version\":2,\"node-version\":16}]"
          fi
  test:
    needs: [verify]
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        include: ${{fromJSON(needs.verify.outputs.environments)}}
    name: 'Test (node: ${{matrix.node-version}})'
    runs-on: ubuntu-latest
    env:
      APPLITOOLS_NIGHTWATCH_MAJOR_VERSION: ${{matrix.framework-version}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/eyes-nightwatch
      - name: Upload testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: nightwatch-test-results-node-${{matrix.node-version}}
          retention-days: 2
          path: |
            ./js/packages/eyes-nightwatch/coverage-tests-metadata.json
            ./js/packages/eyes-nightwatch/coverage-test-report.xml
  publish:
    needs: [test]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Download testing artifacts
        uses: actions/download-artifact@v2
        with:
          name: nightwatch-test-results-node-16
          path: ./js/packages/eyes-nightwatch
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          working-directory: ./js/packages/eyes-nightwatch
          version: ${{inputs.version || github.event.inputs.version}}