name: Publish - sdk browser extension

on:
  workflow_dispatch:
    inputs:
      run-tests:
        description: run tests
        type: boolean
        default: true
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
    secrets:
      NPM_TOKEN:
        required: true
      APPLITOOLS_API_KEY:
        required: true
      APPLITOOLS_API_KEY_READ:
        required: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}

jobs:
  verify:
    name: Verification
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run pre-publish verifications
        shell: bash
        working-directory: ./js/packages/eyes-browser-extension
        run: |
          yarn install
          npx bongo release-pre-check --skip-deps --skip-commit --skip-verify-installed-versions
          npx bongo verify-changelog
  test:
    needs: [verify]
    if: github.event.inputs.run-tests != 'false'
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Setup xvfb
        shell: bash
        working-directory: ./js/packages/eyes-browser-extension
        run: |
          sudo apt-get install -y xvfb
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/eyes-browser-extension
          test-type: xvfb
  publish:
    needs: [test]
    if: |
      always() &&
      (needs.test.result == 'success' || needs.test.result == 'skipped')
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Update version
        id: version
        uses: ./.github/actions/publish
        with:
          working-directory: ./js/packages/eyes-browser-extension
          version: ${{inputs.version || github.event.inputs.version}}
          skip-npm: true
      - name: Publish to GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.version.outputs.tag}}
          files: |
            js/packages/eyes-browser-extension/eyes-browser-extension.zip
