name: Publish - screenshoter

on:
  workflow_dispatch:
    inputs:
      version:
        description: version type
        type: choice
        options: [patch, minor, major]
        default: patch
  workflow_call:
    inputs:
      version:
        description: version type
        type: string
        default: patch
    secrets:
      NPM_TOKEN:
        required: true
      SAUCE_USERNAME:
        required: true
      SAUCE_ACCESS_KEY:
        required: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

jobs:
  verify:
    name: Verification
    runs-on: ubuntu-latest
    outputs:
      environments: ${{steps.prepare.outputs.environments}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run pre-publish verifications
        shell: bash
        working-directory: ./js/packages/screenshoter
        run: |
          yarn install
          npx bongo release-pre-check --skip-deps --skip-commit --skip-verify-installed-versions
  test-it:
    needs: [verify]
    name: 'Test integration'
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/screenshoter
          test-type: it
          setup-type: none
  test-e2e:
    needs: [test-it]
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: web
            os: ubuntu-latest
            jobs: 15
          - name: android
            os: macos-latest
            jobs: 2
          - name: ios
            os: macos-latest
            jobs: 2
    name: 'Test e2e (${{matrix.name}})'
    runs-on: ${{matrix.os}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ./js/packages/screenshoter
          test-type: e2e:${{matrix.name}}
          setup-type: ${{matrix.name}}
          jobs: ${{matrix.jobs}}
          remote: ${{matrix.remote}}
      - name: Upload testing artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshoter-test-results-${{matrix.name}}
          retention-days: 2
          path: ./js/packages/screenshoter/logs
  publish:
    needs: [test-e2e]
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Publish to NPM
        uses: ./.github/actions/publish
        with:
          working-directory: ./js/packages/screenshoter
          version: ${{inputs.version || github.event.inputs.version}}
