name: Test packages

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches-ignore: ['dependabot/**']
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases and variations)
        type: string
        required: true
      test-type:
        description: testing type (unit, it, e2e, coverage, sanity)
        type: string
        required: false
      build-type:
        description: build type
        type: string
        required: false
      setup-type:
        description: setup type
        type: string
        required: false
      links:
        description: package names to link
        required: false
      grep:
        description: grep pattern
        required: false

concurrency: 
  group: ${{github.event_name == 'pull_request' && github.ref || github.run_id }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  DISPLAY: ':99'

jobs:
  setup:
    name: Setup
    if: ${{github.event_name == 'workflow_dispatch' || (github.actor != 'dependabot[bot]' && !github.event.pull_request.draft)}}
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          allow-variations: true
  test:
    needs: setup
    strategy:
      fail-fast: false
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.packages)}}
    runs-on: ${{matrix.os}}
    name: ${{matrix.displayName}}
    env: ${{matrix.env}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - name: Setup xvfb
        if: ${{matrix.xvfb}}
        run: |
          sudo apt-get install -y xvfb
          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          working-directory: ${{matrix.path}}
          test-type: ${{(github.event_name == 'pull_request' && 'sanity') || github.event.inputs.test-type}}
          build-type: ${{github.event.inputs.build-type}}
          setup-type: ${{github.event.inputs.setup-type}}
          links: ${{matrix.links || github.event.inputs.links}}
          grep: ${{github.event.inputs.grep}}
        env:
          APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
          APPLITOOLS_API_KEY_JSSDK: ${{secrets.APPLITOOLS_API_KEY_JSSDK}}
          APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
          AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
      - name: Save testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-${{matrix.name}}
          retention-days: 2
          path: |
            ${{matrix.path}}/coverage-tests-metadata.json
            ${{matrix.path}}/coverage-test-report.xml
