name: Test packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: package names (aliases and variations)
        type: string
        required: true
      type:
        description: testing type (unit, it, e2e, coverage)
        type: string
        required: false
      remote:
        description: remote type
        type: choice
        options: [local, eg]
        default: local
        required: false
      links:
        description: linked package names
        required: false
      linking-depth:
        description: linking depth
        default: '0'
        required: false
      grep:
        description: grep pattern
        required: false
env:
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
  DISPLAY: ':99'
  STDOUT_LEVEL: 1
  FORCE_COLOR: 3
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          allow-variations: true
      - name: Debug log
        run: echo "${{toJSON(github.event.inputs)}}"
  test:
    needs: setup
    strategy:
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.packages)}}
      fail-fast: false
    runs-on: ubuntu-latest
    name: ${{matrix.displayName}}
    env: ${{matrix.env}}
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2 
        with:
          node-version: lts/*
      - name: Setup xvfb
        run: |
          sudo apt-get install -y xvfb
          Xvfb -ac $DISPLAY -screen 0 1280x1024x16 &
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{matrix.package}}
          type: ${{github.event.inputs.type}}
          remote: ${{github.event.inputs.remote}}
          install: ${{matrix.install}}
          links: ${{github.event.inputs.links}}
          linking-depth: ${{github.event.inputs['linking-depth']}}
          grep: ${{github.event.inputs.grep}}
        env:
          CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
          CVG_TESTS_EG_REMOTE: ${{secrets.CVG_TESTS_EG_REMOTE}}
          APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
          APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
          APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
          SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
          SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
      - name: Save testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-${{matrix.name}}
          retention-days: 2
          path: |
            packages/${{matrix.package}}/coverage-tests-metadata.json
            packages/${{matrix.package}}/coverage-test-report.xml
