name: Test packages

on:
  workflow_dispatch:
    inputs:
      packages:
        description: "package names (aliases and variations)"
        required: true
      links:
        description: "linked packages names"
        default: "eyes-sdk-core"
      linking-depth:
        description: "linking depth"
        default: 0
      grep:
        description: "grep pattern"
env:
  CVG_TESTS_REMOTE: http://localhost:4444/wd/hub
  APPLITOOLS_API_KEY_SDK: ${{secrets.APPLITOOLS_API_KEY_SDK}}
  APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
  APPLITOOLS_API_KEY_READ: ${{secrets.APPLITOOLS_API_KEY_READ}}
  SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}
  SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
  AZURE_STORAGE_CONNECTION_STRING: ${{secrets.AZURE_STORAGE_CONNECTION_STRING}}
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      packages: ${{steps.setup.outputs.packages}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/parser
        id: setup
        with:
          packages: ${{github.event.inputs.packages}}
          allow-modifiers: true
      - name: Debug
        run: |
        echo ${{toJSON(fromJSON(steps.setup.outputs.packages).*)}}
  test:
    needs: setup
    strategy:
      matrix: 
        include: ${{fromJSON(needs.setup.outputs.packages).*}}
      fail-fast: false
    name: ${{matrix.displayName}}
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repository
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Run tests
        uses: ./.github/actions/tests
        with:
          package: ${{matrix.package}}
          install: ${{matrix.install}}
          links: ${{github.event.inputs.links}}
          linking-depth: ${{github.event.inputs['linking-depth']}}
          grep: ${{github.event.inputs.grep}}
        env: ${{matrix.env}}
      - name: Save testing artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-tests-report-${{matrix.name}}
          retention-days: 2
          path: |
            packages/${{matrix.package}}/coverage-tests-metadata.json
            packages/${{matrix.package}}/coverage-test-report.xml
